require('dotenv').config({path:require('path').join(__dirname,'../.env')});
const express=require('express');const cors=require('cors');const helmet=require('helmet');const pool=require('./db');const{migrate}=require('./migrate');const{rateLimit}=require('./middleware/rateLimit');
function validateConfig(){const errors=[];if(!process.env.DATABASE_URL)errors.push('DATABASE_URL is required');if(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32)errors.push('JWT_SECRET must be at least 32 characters');if(!process.env.AUDIT_CHAIN_KEY||process.env.AUDIT_CHAIN_KEY.length<32)errors.push('AUDIT_CHAIN_KEY must be at least 32 characters');if(errors.length)throw new Error(`Configuration error: ${errors.join('; ')}`);}
function createApp(){const app=express();app.disable('x-powered-by');const allowed=new Set((process.env.CORS_ORIGINS||'http://localhost:5173').split(',').map(v=>v.trim()).filter(Boolean));app.use(helmet());app.use(cors({origin(origin,callback){return!origin||allowed.has(origin)?callback(null,true):callback(Object.assign(new Error('Origin is not allowed'),{status:403}));}}));app.use(express.json({limit:'256kb',strict:true}));app.use('/api',rateLimit({max:300,key:req=>`api:${req.ip}`}));
 const mounts=[
 ['/api/auth','./routes/auth'],['/api/quality','./routes/quality','router'],['/api/ai','./routes/ai'],['/api/chips','./routes/chips'],['/api/missions','./routes/missions'],['/api/deployments','./routes/deployments'],['/api/tests','./routes/tests'],['/api/manufacturers','./routes/manufacturers'],['/api/research','./routes/research'],['/api/audit','./routes/audit'],['/api/exports','./routes/exports'],['/api/search','./routes/search'],['/api/admin','./routes/sample_data'],['/api/dashboard','./routes/dashboard'],
 ['/api/gap-ai-thermal-envelope-solver','./routes/gap-ai-thermal-envelope-solver'],['/api/gap-ai-mass-budget-optimizer','./routes/gap-ai-mass-budget-optimizer'],['/api/gap-ai-single-event-upset','./routes/gap-ai-single-event-upset'],['/api/gap-ai-derating-advisor','./routes/gap-ai-derating-advisor'],['/api/gap-ai-test-coverage-gap','./routes/gap-ai-test-coverage-gap'],['/api/gap-nonai-eda-cad-upload','./routes/gap-nonai-eda-cad-upload'],['/api/gap-nonai-tier2-suppliers','./routes/gap-nonai-tier2-suppliers'],['/api/gap-nonai-itar-flags','./routes/gap-nonai-itar-flags'],['/api/gap-nonai-chamber-scheduling','./routes/gap-nonai-chamber-scheduling'],['/api/gap-nonai-orbit-telemetry-ingest','./routes/gap-nonai-orbit-telemetry-ingest'],['/api/cf-chip-digital-twin','./routes/cf-chip-digital-twin'],['/api/cf-itar-collaboration','./routes/cf-itar-collaboration'],['/api/cf-rad-test-plan-gen','./routes/cf-rad-test-plan-gen'],['/api/cf-mission-derating','./routes/cf-mission-derating'],['/api/cf-rad-hard-marketplace','./routes/cf-rad-hard-marketplace'],['/api/rad-test-campaigns','./routes/rad-test-campaigns'],['/api/orbit-environments','./routes/orbit-environments'],['/api/upscreen-lots','./routes/upscreen-lots'],['/api/subsystem-budgets','./routes/subsystem-budgets'],['/api/rad-hard-foundries','./routes/rad-hard-foundries'],['/api/custom-views','./routes/customViews']];
 for(const[path,modulePath,property]of mounts){const loaded=require(modulePath);app.use(path,property?loaded[property]:loaded);}
 app.get('/api/health',(_req,res)=>res.json({ok:true,service:'electronics-in-space'}));app.get('/api/health/readiness',async(_req,res,next)=>{try{await pool.query('SELECT 1');return res.json({ready:true});}catch(error){return next(error);}});app.use('/api',(req,res)=>res.status(404).json({error:'Not found',path:req.path}));app.use((error,_req,res,_next)=>{if(process.env.NODE_ENV!=='test')console.error(error);if(error.type==='entity.too.large')return res.status(413).json({error:'Request body is too large'});if(error instanceof SyntaxError&&error.status===400)return res.status(400).json({error:'Malformed JSON'});if(error.code==='23505')return res.status(409).json({error:'A record with this identifier already exists'});if(['23503','23514','22P02'].includes(error.code))return res.status(400).json({error:'Request violates a data constraint'});const status=Number.isInteger(error.status)?error.status:500;return res.status(status).json({error:status===500?'Internal server error':error.message,details:status<500?error.details:undefined});});return app;}
async function start(){validateConfig();await migrate();const port=Number(process.env.PORT||3008);return createApp().listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`SpaceLab backend running on port ${port}`));}
if(require.main===module)start().catch(error=>{console.error(error.message);pool.end().finally(()=>{process.exitCode=1;});});module.exports={createApp,start,validateConfig};
